---


apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  selector:
    env: dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


---

kind: Service
apiVersion: v1
metadata:
 name: mywebservice
spec:
 selector:
   type: mywebserver
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
 type: NodePort
