---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: metadata-service
        image: ravinderj/metadata:6.0
        ports:
        - containerPort: 8080



---

apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
      - containerPort: 21027
