---

apiVersion: v1
kind: Pod
metadata:
  name: metadata-pod
spec:
  containers:
    - name: metadata-service
      image: ravinderj/metadata:6.0 
      ports:
      - containerPort: 8080
        protocol: TCP
